### ISSUE TITLE
Error: File not found: git@github.com:pantsel/kong-middleman-plugin.git

### ISSUE THREAD

**Issue by rcardoso1981** [pantsel/kong-middleman-plugin#2]
Hi there,

I'm trying to install this custom plugin into my kong docker container but when I do the final step:
luarocks install middleman

I got this:
Warning: Failed searching manifest: Failed extracting manifest file
Installing https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/middleman-0.1.0-1.rockspec

Error: File not found: git@github.com:pantsel/kong-middleman-plugin.git

I've been researching about this error but no luck so far.

**Comment by pantsel** [comment]
@rcardoso1981 , cheers!

**Comment by johnrobertporter** [comment]
I am having almost the exact same issue now.

I have even logged into the kong container and tried to run `luarocks install middleman` manually, and receive:

```
# luarocks install middleman
Warning: The directory '/root/.cache/luarocks' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing /usr/local/bin/luarocks with sudo, you may want sudo's -H flag.
Installing https://luarocks.org/middleman-0.1.0-1.rockspec

Error: File not found: git@github.com:pantsel/kong-middleman-plugin.git
```

**Comment by dhbmedanis** [comment]
Having the same issue Error: File not found: git@github.com:pantsel/kong-middleman-plugin.git.

Does anyone get a solution for this ?

**Comment by phamhoaithuong** [comment]
i have same issuse
