### ISSUE TITLE
the body_data is null

### ISSUE THREAD

**Issue by orientzc** [pantsel/kong-middleman-plugin#6]
hello,
i am trying to use the plugin, but i am facing this problem:
the body_data is null.
details:
![qq 20180205213957](https://user-images.githubusercontent.com/17718632/35807244-2974d170-0abd-11e8-96c3-f63af9989a6b.png)

The Kong version we are using is 0.11.2. 
and the origin request and response:
![image](https://user-images.githubusercontent.com/17718632/35807293-433cf92a-0abd-11e8-8d27-735de9c14b61.png)

Can someone suggest what could we be missing?

thank you!

**Comment by Sverik** [comment]
Seems to be a simple issue of not reading the body first. I have fixed it, here's the pull request:
https://github.com/pantsel/kong-middleman-plugin/pull/8

**Comment by pantsel** [comment]
@Sverik , thanks for the contribution man!
Cheers.
